### ISSUE TITLE
Make roadmap

### ISSUE THREAD

**Issue by gjain-7** [Web-Team-IITI-Gymkhana/tpc-frontend#3]
- [x] Create README.md
- [x] Create a wiki. Add following sections
  - [x] About
  - [x] Data Model and Flow
  - [x] Technology Stack Selection
  - [x] Repository Structure and Coding Principles
    - Repository Structure
      - Frontend Directory Structure
      - Backend Directory Structure
    - Coding Principles
      - Coding Standards
      - Code Patterns and Conventions
  - [x] Development Workflow
    - Step-by-Step Explanation of the Development Workflow
    - How Code is Developed, Reviewed, and Merged
    - CI/CD Pipeline and Deployment Process
  - [x] Contributing
    - Guidelines for New Developers
    - Setting Up Development Environments
    - How to Contribute

**Comment by gjain-7** [comment]
- [ ] Create README.md
- [ ] Create a wiki. Add following sections
  - [ ] About
  - [ ] Data Model and Flow
  - [ ] Technology Stack Selection
  - [ ] Repository Structure and Coding Principles
    - Repository Structure
      - Frontend Directory Structure
      - Backend Directory Structure
    - Coding Principles
      - Coding Standards
      - Code Patterns and Conventions
  - [ ] Development Workflow
    - Step-by-Step Explanation of the Development Workflow
    - How Code is Developed, Reviewed, and Merged
    - CI/CD Pipeline and Deployment Process
  - [ ] Contributing
    - Guidelines for New Developers
    - Setting Up Development Environments
    - How to Contribute
- [ ]  Set up development workflow pipelines for
  - [ ] Auto deployment for frontend (issue: server firewall blocks github)
  - [ ] backend (same issue)
